package rules

import com.sbz.models.Receipt;
import com.sbz.models.ReceiptDiscount;
import java.time.ZonedDateTime;
import java.util.Date;
import java.time.Instant;

rule "osnovni popust 5% na racun ukoliko ukupna vrednost narucenih artikala prelazi 200000"
	agenda-group "receipt"
    when 
    	$r:	Receipt($items: items)
       $tp: Double(doubleValue>200000) 
		    	from accumulate(Item($tpi : totalPrice) from $items, sum($tpi))
    then
    	System.out.println("Osnovni popust 5% na ceo racun");
        $r.getDiscounts().add(new ReceiptDiscount($r, 5, "BASE")); 
end

rule "dodatni popust 1% ukoliko je kupac korisnik sistema vise od 2 godine"
	agenda-group "receipt"
    when 
    	$r:	Receipt(customer.registered.toInstant().isBefore(ZonedDateTime.now().plusYears(-2).toInstant()))
    then
    	System.out.println("Dodatni popust 1% na ceo racun - 2 godine");
        $r.getDiscounts().add(new ReceiptDiscount($r, 1, "ADDITIONAL")); 
end

rule "dodatni popust 1% ukoliko kupac pripada kategoriji srebrni ili zlatni kupac"
	agenda-group "receipt"
    when 
    	$r:	Receipt(customer.category.name=="GOLD" || customer.category.name=="SILVER")
    then
    	System.out.println("Dodatni popust 1% na ceo racun - zlatni/srebrni");
        $r.getDiscounts().add(new ReceiptDiscount($r, 1, "ADDITIONAL")); 
end

rule "finalni popust za racun i izracunavanje konacne cene racuna"
	agenda-group "receipt"
	salience -1
	when
		$r:	Receipt($discounts: discounts, $items: items)
	   $rd: Integer() 
		    	from accumulate(ReceiptDiscount($d : discount) from $discounts, sum($d))
	  $ifp: Double() 
		    	from accumulate(Item($fp : finalPrice) from $items, sum($fp))
	then
		$r.setDiscount($rd);
		$r.setFinalPrice($ifp-$ifp*$rd/100);
end
